name: Build snap

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create snap package
    runs-on: ubuntu-20.04 

    steps:
      - name: Checking out repo
        uses: actions/checkout@v3.0.1
      # - name: Install lxd
      #   run: |
      #     sudo lxd init --auto
      #     sudo usermod --append --groups lxd $USER
      #     sg lxd -c 'lxc version'
      # - name: Install snapcraft
      #   run: sudo snap install snapcraft --classic
      # - name: Build snap
      #   run: |
      #     sg lxd -c 'snapcraft --use-lxd'
      #     sudo mv nockberge*.snap nockberge.snap
      # - name: Uploading snap
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: nockberge.snap
      #     path: nockberge.snap
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge